//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_hotel_price
    {
        public int id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string requirement { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
