//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_list_email
    {
        public int id { get; set; }
        public string cemail { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
