//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string address { get; set; }
        public string dis { get; set; }
        public string provin { get; set; }
        public string des { get; set; }
        public string website { get; set; }
        public string contact { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<int> minprice { get; set; }
        public Nullable<byte> haspromotion { get; set; }
        public string note { get; set; }
    }
}
