//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf_booking_invoice
    {
        public int id { get; set; }
        public int idbooking { get; set; }
        public string playdate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> pricebuggies { get; set; }
        public Nullable<int> priceextralhole { get; set; }
        public Nullable<int> priceextralbuggies { get; set; }
        public Nullable<int> numofguest { get; set; }
        public Nullable<int> numofbuggies { get; set; }
        public Nullable<int> totalprice { get; set; }
        public string noteextrafee { get; set; }
    }
}
