//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf_booking
    {
        public int id { get; set; }
        public string idsession { get; set; }
        public int idgolf { get; set; }
        public string golfname { get; set; }
        public string provin { get; set; }
        public string cname { get; set; }
        public string cemail { get; set; }
        public string cphone { get; set; }
        public string caddress { get; set; }
        public Nullable<int> holes { get; set; }
        public Nullable<int> buggies { get; set; }
        public Nullable<int> numofbuggies { get; set; }
        public Nullable<int> numofguest { get; set; }
        public string checkin { get; set; }
        public string teetime { get; set; }
        public Nullable<int> dateplay { get; set; }
        public string note { get; set; }
        public string paymenttype { get; set; }
        public string status { get; set; }
        public string statusadmin { get; set; }
        public Nullable<int> countmail { get; set; }
        public Nullable<System.DateTime> datebook { get; set; }
        public Nullable<int> totalprice { get; set; }
        public Nullable<int> typebook { get; set; }
    }
}
