//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_choupon
    {
        public int id { get; set; }
        public Nullable<int> idhotel { get; set; }
        public string hotelname { get; set; }
        public string provin { get; set; }
        public int idroom { get; set; }
        public string roomname { get; set; }
        public Nullable<int> chouponprice { get; set; }
        public Nullable<int> total { get; set; }
        public string facility1 { get; set; }
        public string facility2 { get; set; }
        public string facility3 { get; set; }
        public string facility4 { get; set; }
        public string facility5 { get; set; }
        public string facility6 { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
