//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_room_price
    {
        public int id { get; set; }
        public int idhotel { get; set; }
        public string hotelname { get; set; }
        public int idroom { get; set; }
        public string roomname { get; set; }
        public int price { get; set; }
        public string month { get; set; }
        public Nullable<byte> show { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
