//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_booking_invoice
    {
        public int id { get; set; }
        public int idbooking { get; set; }
        public string fromdate { get; set; }
        public string todate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> numofroom { get; set; }
        public Nullable<int> totalday { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> totalextrabed { get; set; }
        public Nullable<int> totalextraother { get; set; }
        public Nullable<int> totalprice { get; set; }
    }
}
