//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelbookingEntities : DbContext
    {
        public hotelbookingEntities()
            : base("name=hotelbookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<catnew> catnews { get; set; }
        public DbSet<company_address> company_address { get; set; }
        public DbSet<company_banking> company_banking { get; set; }
        public DbSet<company_introduction> company_introduction { get; set; }
        public DbSet<customer_feedback> customer_feedback { get; set; }
        public DbSet<customer_hotel_price> customer_hotel_price { get; set; }
        public DbSet<customer_list_email> customer_list_email { get; set; }
        public DbSet<golf> golves { get; set; }
        public DbSet<golf_booking> golf_booking { get; set; }
        public DbSet<golf_booking_invoice> golf_booking_invoice { get; set; }
        public DbSet<golf_choupon> golf_choupon { get; set; }
        public DbSet<golf_payment_info> golf_payment_info { get; set; }
        public DbSet<golf_price> golf_price { get; set; }
        public DbSet<golf_promotion> golf_promotion { get; set; }
        public DbSet<golf_rule> golf_rule { get; set; }
        public DbSet<hotel> hotels { get; set; }
        public DbSet<hotel_booking> hotel_booking { get; set; }
        public DbSet<hotel_booking_invoice> hotel_booking_invoice { get; set; }
        public DbSet<hotel_choupon> hotel_choupon { get; set; }
        public DbSet<hotel_facility> hotel_facility { get; set; }
        public DbSet<hotel_image> hotel_image { get; set; }
        public DbSet<hotel_payment_info> hotel_payment_info { get; set; }
        public DbSet<hotel_room_price> hotel_room_price { get; set; }
        public DbSet<hotel_rule> hotel_rule { get; set; }
        public DbSet<hotel_service> hotel_service { get; set; }
        public DbSet<hotline> hotlines { get; set; }
        public DbSet<list_address> list_address { get; set; }
        public DbSet<list_facilities> list_facilities { get; set; }
        public DbSet<list_provin> list_provin { get; set; }
        public DbSet<list_services> list_services { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<slide> slides { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<hotel_room> hotel_room { get; set; }
        public DbSet<hotel_promotion> hotel_promotion { get; set; }
    }
}
