//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_booking
    {
        public int id { get; set; }
        public string idsession { get; set; }
        public int idhotel { get; set; }
        public string hotelname { get; set; }
        public string provin { get; set; }
        public Nullable<int> idroom { get; set; }
        public string roomname { get; set; }
        public Nullable<int> numofroom { get; set; }
        public Nullable<int> numofguest { get; set; }
        public Nullable<int> fromdate { get; set; }
        public Nullable<int> todate { get; set; }
        public System.DateTime datebook { get; set; }
        public string cname { get; set; }
        public string cphone { get; set; }
        public string cemail { get; set; }
        public string caddress { get; set; }
        public string cnote { get; set; }
        public string cip { get; set; }
        public string status { get; set; }
        public Nullable<int> typebook { get; set; }
        public string paymenttype { get; set; }
        public string statusadmin { get; set; }
        public Nullable<int> countmail { get; set; }
        public Nullable<byte> extrabedfee { get; set; }
        public Nullable<byte> extraotherfee { get; set; }
        public Nullable<int> totalprice { get; set; }
    }
}
