//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_room
    {
        public int id { get; set; }
        public int idhotel { get; set; }
        public string hotelname { get; set; }
        public string roomname { get; set; }
        public Nullable<int> square { get; set; }
        public Nullable<int> price { get; set; }
        public string breakfast { get; set; }
        public Nullable<byte> extrabed { get; set; }
        public Nullable<int> maxofadult { get; set; }
        public Nullable<byte> nonsmoking { get; set; }
        public Nullable<int> noofroom { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<int> extrabedfee { get; set; }
        public Nullable<int> extraotherfee { get; set; }
        public string notefee { get; set; }
        public Nullable<byte> showprice { get; set; }
    }
}
