//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string des { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string hcheckin { get; set; }
        public string hcheckout { get; set; }
        public string include { get; set; }
        public string dis { get; set; }
        public string provin { get; set; }
        public Nullable<int> rate { get; set; }
        public string ruleroom { get; set; }
        public string ruleextra { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public System.Data.Spatial.DbGeography geocode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> dateid { get; set; }
        public Nullable<int> minprice { get; set; }
        public Nullable<byte> haspromotion { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<int> totalviews { get; set; }
        public Nullable<byte> invisibleprice { get; set; }
    }
}
